name: Reusable .NET Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display message
        run: |
          echo "Reusable .NET workflow is running"
          echo "Version: v1.0.0"
